{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from ...server.automl.neural_network.neural_network import NeuralNetwork\n",
    "from ...server.automl.neural_network.fc_layer import FCLayer\n",
    "from ...server.automl.neural_network.activation_layer import ActivationLayer\n",
    "from ...server.automl.neural_network.activation_functions import tanh, tanh_derivative, relu, relu_derivative\n",
    "from ...server.automl.neural_network.loss_functions import mse, mse_derivative\n",
    "from ray import tune\n",
    "from ray.tune.schedulers import AsyncHyperBandScheduler\n",
    "from ray.tune.suggest import ConcurrencyLimiter\n",
    "from ray.tune.suggest.bayesopt import BayesOptSearch\n",
    "from sklearn.datasets import load_diabetes\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from sklearn.neural_network import MLPRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(442, 10) (442,)\n",
      "(353, 10) (89, 10) (353,) (89,)\n"
     ]
    }
   ],
   "source": [
    "#Lodaing data\n",
    "X, Y = load_diabetes(return_X_y=True)\n",
    "print(X.shape, Y.shape)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)\n",
    "#Normalizing data\n",
    "scaler = StandardScaler()\n",
    "scaler.fit(X_train)\n",
    "X_train = scaler.transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "network = NeuralNetwork()\n",
    "network.add(FCLayer(X_train.shape[1], 5))\n",
    "network.add(ActivationLayer(tanh, tanh_derivative))\n",
    "network.add(FCLayer(5, 2))\n",
    "network.add(ActivationLayer(tanh, tanh_derivative))\n",
    "network.add(FCLayer(2, 1))\n",
    "network.use(mse, mse_derivative)\n",
    "network.fit(X_train, y_train, epochs=2000, learning_rate=0.1)\n",
    "y_pred = np.array(network.predict(X_test))\n",
    "print(y_test, y_test.shape)\n",
    "print(y_pred, y_pred.shape)\n",
    "print(mean_squared_error(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "clf = MLPRegressor(solver='lbfgs', alpha=0.1,\n",
    "                                            hidden_layer_sizes=(5,2),\n",
    "                                            max_iter=2000,activation='relu')\n",
    "clf.fit(X_train, y_train)\n",
    "y_pred = clf.predict(X_test)\n",
    "print(mean_squared_error(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Function For BayesOpt\n",
    "def my_func(config, reporter):  # add the reporter parameter\n",
    "  # report the configuration\n",
    "  network = NeuralNetwork()\n",
    "  network.add(FCLayer(X_train.shape[1], 5))\n",
    "  network.add(ActivationLayer(tanh, tanh_derivative))\n",
    "  network.add(FCLayer(5, 2))\n",
    "  network.add(ActivationLayer(tanh, tanh_derivative))\n",
    "  network.add(FCLayer(2, 1))\n",
    "  network.use(mse, mse_derivative)\n",
    "  network.fit(X_train, y_train, epochs=1000, learning_rate=config[\"alpha\"])\n",
    "  y_pred = np.array(network.predict(X_test))\n",
    "  print(y_pred)\n",
    "  reporter(config, mean_loss = mean_squared_error(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\services.py:238: UserWarning: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`. To disable this message, set RAY_DISABLE_IMPORT_WARNING env var to '1'.\n",
      "  warnings.warn(warning_message)\n",
      "2022-05-10 05:32:30,525\tWARNING bayesopt.py:397 -- BayesOpt does not support specific sampling methods. The Uniform sampler will be dropped.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 5.9/7.9 GiB<br>Using AsyncHyperBand: num_stopped=0\n",
       "Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None<br>Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/1.55 GiB heap, 0.0/0.78 GiB objects<br>Result logdir: C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp<br>Number of trials: 1/10 (1 PENDING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  alpha</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_d27c419d</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">3.74546</td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-05-10 05:32:30,768\tERROR syncer.py:72 -- Log sync requires rsync to be installed.\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\loss_functions.py:6: RuntimeWarning: overflow encountered in power\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   return np.mean(np.power(y_true-y_pred, 2));\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\loss_functions.py:6: RuntimeWarning: overflow encountered in power\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   return np.mean(np.power(y_true-y_pred, 2));\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\loss_functions.py:6: RuntimeWarning: overflow encountered in power\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   return np.mean(np.power(y_true-y_pred, 2));\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "2022-05-10 05:33:40,006\tERROR trial_runner.py:773 -- Trial my_func_d27c419d: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=16564, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x0000026CFBBC41F0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=16564, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x0000026CFBBC41F0>)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_d27c419d:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 6.3/7.9 GiB<br>Using AsyncHyperBand: num_stopped=0\n",
       "Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None<br>Resources requested: 3.0/8 CPUs, 0/0 GPUs, 0.0/1.55 GiB heap, 0.0/0.78 GiB objects<br>Result logdir: C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp<br>Number of trials: 4/10 (1 ERROR, 3 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  alpha</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_d295ba33</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">9.50715</td></tr>\n",
       "<tr><td>my_func_d2a92c58</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">7.31997</td></tr>\n",
       "<tr><td>my_func_d2bc7340</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">5.98662</td></tr>\n",
       "<tr><td>my_func_d27c419d</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">3.74546</td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_d27c419d</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_d27c419d_1_alpha=3.7455,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-05-10_05-32-30\\error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m 2022-05-10 05:33:39,942\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m [[nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=16564)\u001b[0m  [nan]]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-05-10 05:33:40,598\tERROR trial_runner.py:773 -- Trial my_func_d295ba33: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=18516, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x000001C17CBD41C0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=18516, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x000001C17CBD41C0>)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m 2022-05-10 05:33:40,567\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_d295ba33:\n",
      "  {}\n",
      "  \n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m [[nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=18516)\u001b[0m  [nan]]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m 2022-05-10 05:33:41,095\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "2022-05-10 05:33:41,190\tERROR trial_runner.py:773 -- Trial my_func_d2a92c58: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=15460, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x000001DCD9CD41C0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=15460, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x000001DCD9CD41C0>)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m [[nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=15460)\u001b[0m  [nan]]\n",
      "Result for my_func_d2a92c58:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-05-10 05:33:41,349\tERROR trial_runner.py:773 -- Trial my_func_d2bc7340: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1621, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=2688, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x0000014BD3FC21C0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 178, in train_buffered\n",
      "    result = self.train()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 379, in step\n",
      "    self._report_thread_runner_error(block=True)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 526, in _report_thread_runner_error\n",
      "    raise TuneError(\n",
      "ray.tune.error.TuneError: Trial raised an exception. Traceback:\n",
      "\u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=2688, ip=192.168.1.105, repr=<types.ImplicitFunc object at 0x0000014BD3FC21C0>)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "    self._entrypoint()\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "    return self._trainable_func(self.config, self._status_reporter,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "    output = fn()\n",
      "  File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "    y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "    _assert_all_finite(array,\n",
      "  File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "    raise ValueError(\n",
      "ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m 2022-05-10 05:33:41,285\tERROR function_runner.py:266 -- Runner Thread raised error.\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m Exception in thread Thread-2:\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     self.run()\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 279, in run\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 260, in run\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     self._entrypoint()\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 328, in entrypoint\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     return self._trainable_func(self.config, self._status_reporter,\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\function_runner.py\", line 594, in _trainable_func\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     output = fn()\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"<ipython-input-3-d116da951592>\", line 14, in my_func\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 335, in mean_squared_error\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     y_type, y_true, y_pred, multioutput = _check_reg_targets(\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_regression.py\", line 90, in _check_reg_targets\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     return f(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 663, in check_array\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     _assert_all_finite(array,\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m   File \"c:\\Users\\Public\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 103, in _assert_all_finite\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m ValueError: Input contains NaN, infinity or a value too large for dtype('float64').\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_d2bc7340:\n",
      "  {}\n",
      "  \n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m [[nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]\n",
      "\u001b[2m\u001b[36m(pid=2688)\u001b[0m  [nan]]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=19800)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\loss_functions.py:6: RuntimeWarning: overflow encountered in power\n",
      "\u001b[2m\u001b[36m(pid=19800)\u001b[0m   return np.mean(np.power(y_true-y_pred, 2));\n",
      "\u001b[2m\u001b[36m(pid=19800)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=19800)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "\u001b[2m\u001b[36m(pid=21516)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\loss_functions.py:6: RuntimeWarning: overflow encountered in power\n",
      "\u001b[2m\u001b[36m(pid=21516)\u001b[0m   return np.mean(np.power(y_true-y_pred, 2));\n",
      "\u001b[2m\u001b[36m(pid=21516)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=21516)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "\u001b[2m\u001b[36m(pid=23780)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\loss_functions.py:6: RuntimeWarning: overflow encountered in power\n",
      "\u001b[2m\u001b[36m(pid=23780)\u001b[0m   return np.mean(np.power(y_true-y_pred, 2));\n",
      "\u001b[2m\u001b[36m(pid=23780)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=23780)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "\u001b[2m\u001b[36m(pid=14360)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\loss_functions.py:6: RuntimeWarning: overflow encountered in power\n",
      "\u001b[2m\u001b[36m(pid=14360)\u001b[0m   return np.mean(np.power(y_true-y_pred, 2));\n",
      "\u001b[2m\u001b[36m(pid=14360)\u001b[0m c:\\Users\\Mohamed Ghallab\\Desktop\\GP\\AutoML\\notebooks\\neural_network_generation\\activation_layer.py:21: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(pid=14360)\u001b[0m   return self.activation_function_derivative(self.input) * output_error\n",
      "2022-05-10 05:34:11,704\tWARNING tune.py:518 -- SIGINT received (e.g. via Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C one more time (or send SIGINT/SIGKILL/SIGTERM) to skip. \n"
     ]
    }
   ],
   "source": [
    "#Bayesian Optimization\n",
    "algo = BayesOptSearch(utility_kwargs={\"kind\": \"ucb\", \"kappa\": 2.5, \"xi\": 0.0})\n",
    "algo = ConcurrencyLimiter(algo, max_concurrent=4)\n",
    "scheduler = AsyncHyperBandScheduler()\n",
    "analysis = tune.run(\n",
    "        my_func,\n",
    "        name=\"my_exp\",\n",
    "        metric=\"mean_loss\",\n",
    "        stop={\"mean_loss\": 3000},\n",
    "        mode=\"min\",\n",
    "        search_alg=algo,\n",
    "        scheduler=scheduler,\n",
    "        num_samples=10,\n",
    "        config={\n",
    "            \"steps\": 100,\n",
    "            \"input_dim\": X_train.shape[1],\n",
    "            \"hidden_dim\": 5,\n",
    "            \n",
    "            \"output_dim\": 1,\n",
    "            \"alpha\": tune.uniform(0.0001, 10),\n",
    "        },\n",
    "    )\n",
    "\n",
    "print(\"Best hyperparameters found were: \", analysis.best_config)"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "7b9bf3d753fefe854781e52229fcc2b6d37fd5cec0eed166290fc2ac2cd3389d"
  },
  "kernelspec": {
   "display_name": "Python 3.8.8 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
