{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ...server.automl.neural_network.neural_network import NeuralNetwork\n",
    "from ...server.automl.neural_network.fc_layer import FCLayer\n",
    "from ...server.automl.neural_network.activation_layer import ActivationLayer\n",
    "from ...server.automl.neural_network.activation_functions import tanh, tanh_derivative, relu, relu_derivative\n",
    "from ...server.automl.neural_network.loss_functions import mse, mse_derivative\n",
    "from ray import tune\n",
    "from ray.tune.schedulers import AsyncHyperBandScheduler\n",
    "from ray.tune.suggest import ConcurrencyLimiter\n",
    "from ray.tune.suggest.bayesopt import BayesOptSearch\n",
    "from sklearn.datasets import load_diabetes\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import mean_squared_error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(442, 10) (442,)\n",
      "(353, 10) (89, 10) (353,) (89,)\n"
     ]
    }
   ],
   "source": [
    "X, Y = load_diabetes(return_X_y=True)\n",
    "print(X.shape, Y.shape)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)\n",
    "print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def my_func(config, reporter):  # add the reporter parameter\n",
    "      # report the configuration\n",
    "    network = NeuralNetwork()\n",
    "    network.add(FCLayer(config['input_dim'], config['hidden_dim']))\n",
    "    network.add(ActivationLayer(relu, relu_derivative))\n",
    "    network.add(FCLayer(config['hidden_dim'], 2))\n",
    "    network.add(ActivationLayer(relu, relu_derivative))\n",
    "    network.add(FCLayer(2, config['output_dim']))\n",
    "    network.add(ActivationLayer(relu, relu_derivative))\n",
    "    network.use(mse, mse_derivative)\n",
    "    network.fit(X_train, y_train, epochs=90000, learning_rate=config[\"alpha\"])\n",
    "    y_pred = network.predict(X_train)\n",
    "    reporter(config, mean_loss = mean_squared_error(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\services.py:238: UserWarning: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`. To disable this message, set RAY_DISABLE_IMPORT_WARNING env var to '1'.\n",
      "  warnings.warn(warning_message)\n",
      "2022-04-14 05:33:50,097\tWARNING bayesopt.py:397 -- BayesOpt does not support specific sampling methods. The Uniform sampler will be dropped.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 6.9/7.9 GiB<br>Using AsyncHyperBand: num_stopped=0\n",
       "Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None<br>Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/0.83 GiB heap, 0.0/0.42 GiB objects<br>Result logdir: C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp<br>Number of trials: 1/10 (1 PENDING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  alpha</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_b33f7da6</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">3.74546</td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:33:50,521\tERROR syncer.py:72 -- Log sync requires rsync to be installed.\n",
      "2022-04-14 05:33:52,278\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 63c321026544a2981c4fc55201000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m 2022-04-14 05:33:52,268\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m 2022-04-14 05:33:52,274\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=13076, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=13076)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "2022-04-14 05:33:52,412\tERROR trial_runner.py:773 -- Trial my_func_b36193d5: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=5880, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "2022-04-14 05:33:52,418\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID b8fc64003c846091c1666ba701000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m 2022-04-14 05:33:52,405\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m 2022-04-14 05:33:52,408\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=5880, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=5880)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "2022-04-14 05:33:52,537\tERROR trial_runner.py:773 -- Trial my_func_b3760bbd: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=2740, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "2022-04-14 05:33:52,541\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID e016b284b601c807572eb72601000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m 2022-04-14 05:33:52,527\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m 2022-04-14 05:33:52,531\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=2740, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=2740)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b36193d5:\n",
      "  {}\n",
      "  \n",
      "Result for my_func_b3760bbd:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:33:52,772\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 494210fedae1421d29b0296001000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m 2022-04-14 05:33:52,755\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m 2022-04-14 05:33:52,760\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=13796, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=13796)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "2022-04-14 05:33:52,904\tERROR trial_runner.py:773 -- Trial my_func_b38eacd6: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=13796, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b38eacd6:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:33:54,344\tERROR trial_runner.py:773 -- Trial my_func_b33f7da6: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=13076, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b33f7da6:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:33:55,415\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 6c716bc409b9f7dd8a58502901000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "2022-04-14 05:33:55,422\tERROR trial_runner.py:773 -- Trial my_func_b488dc27: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=15216, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b488dc27:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m 2022-04-14 05:33:55,403\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m 2022-04-14 05:33:55,410\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=15216, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=15216)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 6.9/7.9 GiB<br>Using AsyncHyperBand: num_stopped=0\n",
       "Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None<br>Resources requested: 3.0/8 CPUs, 0/0 GPUs, 0.0/0.83 GiB heap, 0.0/0.42 GiB objects<br>Result logdir: C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp<br>Number of trials: 9/10 (5 ERROR, 1 PENDING, 3 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  alpha</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_b4a26d2b</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">1.56003</td></tr>\n",
       "<tr><td>my_func_b4ce1a31</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">0.58093</td></tr>\n",
       "<tr><td>my_func_b5aa0c5f</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">8.66177</td></tr>\n",
       "<tr><td>my_func_b64f510a</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">6.01119</td></tr>\n",
       "<tr><td>my_func_b33f7da6</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">3.74546</td></tr>\n",
       "<tr><td>my_func_b36193d5</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">9.50715</td></tr>\n",
       "<tr><td>my_func_b3760bbd</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">7.31997</td></tr>\n",
       "<tr><td>my_func_b38eacd6</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">5.98662</td></tr>\n",
       "<tr><td>my_func_b488dc27</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">1.56027</td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 5<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_b33f7da6</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b33f7da6_1_alpha=3.7455,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt</td></tr>\n",
       "<tr><td>my_func_b36193d5</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b36193d5_2_alpha=9.5071,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt</td></tr>\n",
       "<tr><td>my_func_b3760bbd</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b3760bbd_3_alpha=7.32,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt  </td></tr>\n",
       "<tr><td>my_func_b38eacd6</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b38eacd6_4_alpha=5.9866,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt</td></tr>\n",
       "<tr><td>my_func_b488dc27</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b488dc27_5_alpha=1.5603,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-52\\error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:33:55,713\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 0eefe37444e31aba62a0592901000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "2022-04-14 05:33:55,726\tERROR trial_runner.py:773 -- Trial my_func_b4a26d2b: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=17340, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m 2022-04-14 05:33:55,707\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m 2022-04-14 05:33:55,716\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=17340, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=17340)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b4a26d2b:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:33:56,004\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 823c62e7f68d4a4f7e97407301000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "2022-04-14 05:33:56,010\tERROR trial_runner.py:773 -- Trial my_func_b4ce1a31: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=536, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m 2022-04-14 05:33:55,988\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m 2022-04-14 05:33:55,997\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=536, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=536)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b4ce1a31:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:33:57,469\tERROR trial_runner.py:773 -- Trial my_func_b5aa0c5f: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=11228, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "2022-04-14 05:33:57,471\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID ce354997305b00436b3a9b3901000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m 2022-04-14 05:33:57,459\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m 2022-04-14 05:33:57,462\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=11228, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=11228)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b5aa0c5f:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:34:02,699\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID cfbc4671b3be15c4f091579d01000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "2022-04-14 05:34:02,703\tERROR trial_runner.py:773 -- Trial my_func_b64f510a: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=15636, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b64f510a:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 6.8/7.9 GiB<br>Using AsyncHyperBand: num_stopped=0\n",
       "Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None<br>Resources requested: 1.0/8 CPUs, 0/0 GPUs, 0.0/0.83 GiB heap, 0.0/0.42 GiB objects<br>Result logdir: C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp<br>Number of trials: 10/10 (9 ERROR, 1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  alpha</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_b68a35dc</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">7.08075</td></tr>\n",
       "<tr><td>my_func_b33f7da6</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">3.74546</td></tr>\n",
       "<tr><td>my_func_b36193d5</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">9.50715</td></tr>\n",
       "<tr><td>my_func_b3760bbd</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">7.31997</td></tr>\n",
       "<tr><td>my_func_b38eacd6</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">5.98662</td></tr>\n",
       "<tr><td>my_func_b488dc27</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">1.56027</td></tr>\n",
       "<tr><td>my_func_b4a26d2b</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">1.56003</td></tr>\n",
       "<tr><td>my_func_b4ce1a31</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">0.58093</td></tr>\n",
       "<tr><td>my_func_b5aa0c5f</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">8.66177</td></tr>\n",
       "<tr><td>my_func_b64f510a</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">6.01119</td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 9<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                 </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_b33f7da6</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b33f7da6_1_alpha=3.7455,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt </td></tr>\n",
       "<tr><td>my_func_b36193d5</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b36193d5_2_alpha=9.5071,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt </td></tr>\n",
       "<tr><td>my_func_b3760bbd</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b3760bbd_3_alpha=7.32,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt   </td></tr>\n",
       "<tr><td>my_func_b38eacd6</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b38eacd6_4_alpha=5.9866,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt </td></tr>\n",
       "<tr><td>my_func_b488dc27</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b488dc27_5_alpha=1.5603,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-52\\error.txt </td></tr>\n",
       "<tr><td>my_func_b4a26d2b</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b4a26d2b_6_alpha=1.56,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-52\\error.txt   </td></tr>\n",
       "<tr><td>my_func_b4ce1a31</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b4ce1a31_7_alpha=0.58093,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-52\\error.txt</td></tr>\n",
       "<tr><td>my_func_b5aa0c5f</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b5aa0c5f_8_alpha=8.6618,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-54\\error.txt </td></tr>\n",
       "<tr><td>my_func_b64f510a</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b64f510a_9_alpha=6.0112,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-55\\error.txt </td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-14 05:34:02,729\tWARNING worker.py:1215 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 820538cfdbc203c69ba4af7201000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "ModuleNotFoundError: No module named 'activation_layer'\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m 2022-04-14 05:34:02,690\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m 2022-04-14 05:34:02,695\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=15636, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=15636)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m 2022-04-14 05:34:02,713\tERROR function_manager.py:505 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 503, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m ModuleNotFoundError: No module named 'activation_layer'\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m 2022-04-14 05:34:02,718\tERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=6452, ip=192.168.1.106)\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m   File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m     raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "\u001b[2m\u001b[36m(pid=6452)\u001b[0m RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n",
      "2022-04-14 05:34:04,754\tERROR trial_runner.py:773 -- Trial my_func_b68a35dc: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 746, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1623, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::ImplicitFunc.__init__()\u001b[39m (pid=6452, ip=192.168.1.106)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 536, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 486, in ray._raylet.execute_task.function_executor\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"C:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 468, in temporary_actor_method\n",
      "    raise RuntimeError(f\"The actor with name {actor_class_name} \"\n",
      "RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for my_func_b68a35dc:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 6.6/7.9 GiB<br>Using AsyncHyperBand: num_stopped=0\n",
       "Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None<br>Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/0.83 GiB heap, 0.0/0.42 GiB objects<br>Result logdir: C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp<br>Number of trials: 10/10 (10 ERROR)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  alpha</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_b33f7da6</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">3.74546</td></tr>\n",
       "<tr><td>my_func_b36193d5</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">9.50715</td></tr>\n",
       "<tr><td>my_func_b3760bbd</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">7.31997</td></tr>\n",
       "<tr><td>my_func_b38eacd6</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">5.98662</td></tr>\n",
       "<tr><td>my_func_b488dc27</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">1.56027</td></tr>\n",
       "<tr><td>my_func_b4a26d2b</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">1.56003</td></tr>\n",
       "<tr><td>my_func_b4ce1a31</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">0.58093</td></tr>\n",
       "<tr><td>my_func_b5aa0c5f</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">8.66177</td></tr>\n",
       "<tr><td>my_func_b64f510a</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">6.01119</td></tr>\n",
       "<tr><td>my_func_b68a35dc</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">7.08075</td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 10<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name      </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                                                 </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>my_func_b33f7da6</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b33f7da6_1_alpha=3.7455,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt </td></tr>\n",
       "<tr><td>my_func_b36193d5</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b36193d5_2_alpha=9.5071,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt </td></tr>\n",
       "<tr><td>my_func_b3760bbd</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b3760bbd_3_alpha=7.32,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt   </td></tr>\n",
       "<tr><td>my_func_b38eacd6</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b38eacd6_4_alpha=5.9866,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-50\\error.txt </td></tr>\n",
       "<tr><td>my_func_b488dc27</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b488dc27_5_alpha=1.5603,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-52\\error.txt </td></tr>\n",
       "<tr><td>my_func_b4a26d2b</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b4a26d2b_6_alpha=1.56,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-52\\error.txt   </td></tr>\n",
       "<tr><td>my_func_b4ce1a31</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b4ce1a31_7_alpha=0.58093,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-52\\error.txt</td></tr>\n",
       "<tr><td>my_func_b5aa0c5f</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b5aa0c5f_8_alpha=8.6618,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-54\\error.txt </td></tr>\n",
       "<tr><td>my_func_b64f510a</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b64f510a_9_alpha=6.0112,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-55\\error.txt </td></tr>\n",
       "<tr><td>my_func_b68a35dc</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\Mohamed Ghallab\\ray_results\\my_exp\\my_func_b68a35dc_10_alpha=7.0808,hidden_dim=5,input_dim=10,output_dim=1,steps=100_2022-04-14_05-33-55\\error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [my_func_b33f7da6, my_func_b36193d5, my_func_b3760bbd, my_func_b38eacd6, my_func_b488dc27, my_func_b4a26d2b, my_func_b4ce1a31, my_func_b5aa0c5f, my_func_b64f510a, my_func_b68a35dc])",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-4-5daacc43d396>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0malgo\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mConcurrencyLimiter\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0malgo\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmax_concurrent\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m4\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mscheduler\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mAsyncHyperBandScheduler\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m analysis = tune.run(\n\u001b[0m\u001b[0;32m      5\u001b[0m         \u001b[0mmy_func\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m         \u001b[0mname\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"my_exp\"\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Users\\Public\\anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint, _remote)\u001b[0m\n\u001b[0;32m    553\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    554\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m \u001b[1;32mand\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mstate\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0msignal\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSIGINT\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 555\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Trials did not complete\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    556\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    557\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Trials did not complete: %s\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTuneError\u001b[0m: ('Trials did not complete', [my_func_b33f7da6, my_func_b36193d5, my_func_b3760bbd, my_func_b38eacd6, my_func_b488dc27, my_func_b4a26d2b, my_func_b4ce1a31, my_func_b5aa0c5f, my_func_b64f510a, my_func_b68a35dc])"
     ]
    }
   ],
   "source": [
    "algo = BayesOptSearch(utility_kwargs={\"kind\": \"ucb\", \"kappa\": 2.5, \"xi\": 0.0})\n",
    "algo = ConcurrencyLimiter(algo, max_concurrent=4)\n",
    "scheduler = AsyncHyperBandScheduler()\n",
    "analysis = tune.run(\n",
    "        my_func,\n",
    "        name=\"my_exp\",\n",
    "        metric=\"mean_loss\",\n",
    "        mode=\"min\",\n",
    "        search_alg=algo,\n",
    "        scheduler=scheduler,\n",
    "        num_samples=10,\n",
    "        config={\n",
    "            \"steps\": 100,\n",
    "            \"input_dim\": X_train.shape[1],\n",
    "            \"hidden_dim\": 5,\n",
    "            \"output_dim\": 1,\n",
    "            \"alpha\": tune.uniform(0.0001, 10),\n",
    "        },\n",
    "    )\n",
    "\n",
    "print(\"Best hyperparameters found were: \", analysis.best_config)"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "7b9bf3d753fefe854781e52229fcc2b6d37fd5cec0eed166290fc2ac2cd3389d"
  },
  "kernelspec": {
   "display_name": "Python 3.8.8 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
